### ISSUE TITLE
Code example to use the component

### ISSUE THREAD

**Issue by Guba666** [TurboPack/DOSCommand#12]
First a deep thanks for this component.
I'm a newbie here on Git, so pleas excuse me if this is inappropriate or wrong, but
I'm asking for adding some coding examples to use this component.
I'm using Delphi 10.3 Rio Community, and it has been installed flawlessly with the IDE tool.
I'd like to find a coding example to use all the features of the component, that seems very powerful.
Please point me to some coding example or integrate some examples in the sources.
Thank you very much

Sergio

**Comment by costica-moldovanu** [comment]
In DosCommand.pas after History is a section with How to use it and How to call

**Comment by geoffsmith82** [comment]
I have added a demo project in pull request #14.
