### ISSUE TITLE
Failing to start an instance with environment variables

### ISSUE THREAD

**Issue by ghost** [TurboPack/DOSCommand#16]
Trying to use this tool to interact with nodeJS from Delphi, but failing due to
_"ECreateProcessError with message 'Error creating Process: npx hardhat test - (The system cannot find the file specified)'. Process DemoListWindowsDir.exe (17516)"_

Starting CMD on Win10 directly and running the command from any folder in the system works just fine and I made sure the nodeJS install folder is added to the PATH in the system, but it feels like the DOSCommand instance does not get the same permissions or scope to access the windows path.

I've tried various edits in the supplied object properties "Environment" thinking it works as key-value pairs, like so
PATH="C:\Program Files\nodejs"
but all that achieves is crashing bds.exe with an access violation.

This comment in the code seems to hint at the format, despite typos, but that seems to only separate the variables in case there are multiple
_"environmentstrings are devided bei #0"_

How could this be helped?

**Comment by romankassebaum** [comment]
Have you tried to run nodejs inside a command like "cmd.exe /c nodejs..."?

**Comment by ghost** [comment]
> Have you tried to run nodejs inside a command like "cmd.exe /c nodejs..."?

That seemed to have helped, thank you. Though the quotes had to be structured like so
_cmd /c "npx hardhat test"_

It's still throwing some errors, but those seem to be related to my local installation and not with Delphi or DOScommand.
