### ISSUE TITLE
Thread Exception on Terminate

### ISSUE THREAD

**Issue by JamardaDigital** [TurboPack/DOSCommand#2]
I was getting an intermittent thread exception on termination. I fixed by moving:

**FThread.FreeOnTerminate := False;**

from **TDosCommand.Stop** and placed it after the thread is created in **TDosCommand.Execute**.

This seems to fix the issues I've been having. Can someone please confirm.

**Comment by romankassebaum** [comment]
Do you have a demo app to reproduce the issue?

**Comment by JamardaDigital** [comment]
No sorry, my current project is HUGE and it's hard to pull out the bits to make a simple demo. About every other run or so it produced an exception with invalid thread handle. This clued me to the fact that the thread object may have already been released. Looking at FreeOnTerminate it looks like its modifies the object ref count. So it makes sense to call FreeOnTerminate := False right after object creation and before Execute rather than in Stop. Since making this change, I've not seen the exception again.

**Comment by romankassebaum** [comment]
The code doesn't seem to be threadsafe. That's why I moved the FreeOnTerminate := False to the constructor of TDosThread.

Could you please check this?
