### ISSUE TITLE
Invoking command output information loses characters

### ISSUE THREAD

**Issue by Tudsday** [TurboPack/DOSCommand#20]
Command:
D:\Qampp\yt-dlp.exe --format 137,140 -continue --output "down.mkv" "https://www.youtube.com/watch?v=fsG1XaZEa78"
Please refer to the return value of the system cmd form,
![tuesdays_2022530151251](https://user-images.githubusercontent.com/28974521/171320906-153cc536-6749-40a7-9060-cc3e1e59963f.png)

**Comment by romankassebaum** [comment]
TDosCommand converts per default the bytes to an ANSI string. If you have special chars like in your example you have to set the OnCharDecoding event in which you can work with your own encoding.

**Comment by Tudsday** [comment]
> TDosCommand converts per default the bytes to an ANSI string. If you have special chars like in your example you have to set the OnCharDecoding event in which you can work with your own encoding.

function TForm1.dscmnd1CharDecoding(ASender: TObject; ABuf: TStream): string;
var
  Ts:TStrings;
begin
   Ts := TStringList.Create;
   Ts.LoadFromStream(ABuf, TEncoding.Unicode);
  // What should I do? Thanks for your reply.
    Result := (Ts.Text);
    FreeAndNil(Ts);
end;
![QQ截图20220602120612](https://user-images.githubusercontent.com/28974521/171551027-283b6cde-46b1-4886-9145-edbffacf4b04.png)

**Comment by romankassebaum** [comment]
Here is a code fragment, it uses UTF8 instead of Unicode:
...
var
  pBytes: TBytes;
  iLength: Integer;
...
iLength := ABuf.Size;
    if iLength > 0 then
    begin
      SetLength(pBytes, iLength);
      ABuf.Read(pBytes, iLength);
      Result := TEncoding.UTF8.GetString(pBytes);
    end
    else
      Result := '';

**Comment by Tudsday** [comment]
> Here is a code fragment, it uses UTF8 instead of Unicode: ... var pBytes: TBytes; iLength: Integer; ... iLength := ABuf.Size; if iLength > 0 then begin SetLength(pBytes, iLength); ABuf.Read(pBytes, iLength); Result := TEncoding.UTF8.GetString(pBytes); end else Result := '';

![2222](https://user-images.githubusercontent.com/28974521/172079197-4c76f89a-eb27-49ed-9ea0-457747ebf6c8.png)
What should I do?

**Comment by romankassebaum** [comment]
I explained you what to do, I also gave you a code snippet. The rest is up to you. Here is no place for FAQ.
