### ISSUE TITLE
Installation in Delphi 11.2 not working

### ISSUE THREAD

**Issue by baeckerg** [TurboPack/DOSCommand#21]
Hello,

I tried the installation from GetIt and Github in Alexandria 11.2. Registration of the component fails.

I am using delphi in a Windows on Arm environment. Any help would be appreciated.

Kind regards

**Comment by romankassebaum** [comment]
I just tried and it worked perfectly. I used the GitHub version.

Maybe there are some fragments from the GetIt version. Remove them and try again.

**Comment by baeckerg** [comment]
Thanks for the hint - apparently there was some "leftover". Works now
