### ISSUE TITLE
Asserts should be removed

### ISSUE THREAD

**Issue by xelnaga64** [TurboPack/DOSCommand#22]
The assert errors (in DosCommand.pas) appear on user's face. They should be removed.

**Comment by romankassebaum** [comment]
You have to compile in Release mode without assertions for your customers. Then the compiler removes the asserts. And certainly you have to check why there is an assertion.

**Comment by xelnaga64** [comment]
Does GetIt install it in Debug mode?

**Comment by romankassebaum** [comment]
I do not know about GetIt, but here the packages are in Release mode. However, if you compile your own project, and you do not use runtime packages, then you compile the sources with your settings.

I will close the case at this point.

**Comment by xelnaga64** [comment]
Hi. I encountered this error again today and did some digging.

Even when I build the component in Release mode, the assert still shows up. It appears when my DOS command returns a large amount of data that my app obviously can’t handle. I can manually remove the assert from the original source, but please remove this assert on line 690 from DosCommand.pas.

`      Assert(WriteFile(AWritePipe, pBuf.memory^, pBuf.Size, bWrite, nil));`

**Comment by romankassebaum** [comment]
Done.
