### ISSUE TITLE
Thread-Fehler: Das Handele ist ungültig (6)

### ISSUE THREAD

**Issue by Andreas2k** [TurboPack/DOSCommand#5]
Ich erhalte die immer die Fehlermeldung "Thread-Fehler: Das Handele ist ungültig (6)" wenn das mit execute aufgerufene Programm noch läuft wenn z.B. TDosCommand.Stop aufgerufen wird bzw. das Hauptprogramm beendet wird.

Getestet habe ich das unter Windows 10 x64, starten von gohstscript gswin9.21c.exe ohne -dBATCH oder Notepad++.exe

**Comment by romankassebaum** [comment]
I need a test project.
