### ISSUE TITLE
sending virtualkeys to the console

### ISSUE THREAD

**Issue by antoniohanna** [TurboPack/DOSCommand#6]
hello, 
please i need your help,
is there a way to send virtual keyboard strokes to the console ?
i need to send a PAUSE key

the SendLine procedure sends only string .. 
is there a way ?? please

**Comment by AdriaanBoshoff** [comment]
These guys haven't been active for a while. Have you found a solution?

**Comment by romankassebaum** [comment]
I have no idea.
