### ISSUE TITLE
64bit does not build doscommand.o correctly for 10.3

### ISSUE THREAD

**Issue by tonyt73** [TurboPack/DOSCommand#8]
How to fix:
1. The DosCommandCR.cproj doesn't include DosCommand.pas as a source object. So add it.
2. Remove the references to DosCommandDR from packageimports in DosCommandCR.cproj
3. DosCommandCD.cproj - DllSuffix should be 260

See attached files.

[CBuilder.zip](https://github.com/TurboPack/DOSCommand/files/2787144/CBuilder.zip)

**Comment by romankassebaum** [comment]
Fixed.
